.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. coinium_qt test_coinium_qt
clean: FORCE
	$(MAKE) -C .. coinium_qt_clean test_coinium_qt_clean
check: FORCE
	$(MAKE) -C .. test_coinium_qt_check
coinium-qt coinium-qt.exe: FORCE
	 $(MAKE) -C .. coinium_qt
